-- Script Name: V22__create_usp_load_gold_dim_airport.sql
-- Description: Creates the stored procedure that loads gold.dim_airport
--              from silver.airport_clean. Truncate + full load strategy.
--              Surrogate key generated by IDENTITY.
--              Logs execution start, success and errors to etl.etl_log.
-- Author:      Michael Espinosa
-- Date:        2026-06-06
-- Change Log:
--   2026-06-06 | Michael Espinosa | Initial version

CREATE OR REPLACE PROCEDURE gold.usp_load_gold_dim_airport()
LANGUAGE plpgsql
AS $$
DECLARE
    v_log_id INT;
    v_rows   INT;
BEGIN
  v_log_id := etl.ufn_log_start_etl('usp_load_gold_airport');
  RAISE NOTICE '[START] usp_load_gold_airport';

  INSERT INTO gold.dim_airport(
    iata_code, airport_name, city, state,
    country, latitude, longitude, created_at, updated_at)
  SELECT
    iata_code, airport_name, city, state,
    country, latitude, longitude, NOW(), NULL
  FROM silver.airport_clean
  ON CONFLICT (iata_code) DO UPDATE SET
    airport_name = EXCLUDED.airport_name,
    updated_at   = NOW();

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RAISE NOTICE '[SUCCESS] Rows written: %', v_rows;

  CALL etl.usp_log_success_etl(
        p_etl_log_id   := v_log_id,
        p_rows_written := v_rows,
        p_rows_read    := v_rows
    );

EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE '[ERROR] %', SQLERRM;
    CALL etl.usp_log_error_etl(
        p_etl_log_id    := v_log_id,
        p_error_code    := 0,
        p_error_message := SQLERRM
    );
    RAISE;
END;
$$;
